### ISSUE TITLE
Provide cell id info

### ISSUE THREAD

**Issue by andygup** [Esri/cordova-plugin-advanced-geolocation#2]
Investigate including cell id info, for example [GsmCellLocation](http://developer.android.com/reference/android/telephony/gsm/GsmCellLocation.html)

**Comment by roysG** [comment]
it will be great also to collect the neighbours cells and his info.
But pay attention that in some devices the array of the neighbours return empty array or null and the code need to be change.. :)

**Comment by andygup** [comment]
Reference: Android SDK [NeighboringCellInfo](http://developer.android.com/reference/android/telephony/NeighboringCellInfo.html)

**Comment by andygup** [comment]
A note from the Android SDK docs related to NeighboringCellInfo: `This method was deprecated in API level 23. Use (@link getAllCellInfo} which returns a superset of the information from NeighboringCellInfo.`
