### ISSUE TITLE
A simple mistake in build process

### ISSUE THREAD

**Issue by thomaspons** [Esri/cordova-plugin-advanced-geolocation#37]
It's impossible to install the plugin due to a simple mùistake in plugin.xml the ErrorMessages class is not present 

<source-file src="src/com/esri/cordova/geolocation/utils/ErrorMessages.java" target dir="src/com/esri/cordova/geolocation/utils" />

Add this line in the plugin.xml file at line 65 solve the problem.

Best regards, 

Thomas

**Comment by andygup** [comment]
Thanks for the heads-up. I'll take a look.
