### ISSUE TITLE
Feature Request: Running service when application is in the background

### ISSUE THREAD

**Issue by scarabdesign** [Esri/cordova-plugin-advanced-geolocation#40]
I notice the plugin will call onPause when I put the application in the background. However, the application I'm working on is a tracker that returns location information to the central server for the tech/admin teams to locate their drivers. Is it possible to have an option to remove the pause in service?

Also, while I'm asking for things, would it be difficult to put in an optional callback to pass into .stop() and .kill() that will be called when all is said and done?

**Comment by andygup** [comment]
>> option to remove pause

I can investigate it, I have a hunch that it's not possible with how I've architected the current handling of Android 6+ permissions. It may have to wait until such time I can outsource permissions handling to a library like [Dexter](https://github.com/Karumi/Dexter). 

Also, keep in mind this library isn't architected to work in the background. It's intended to be used as an always-on, primary sensor and can subject a device to high-cpu, memory and battery consumption. There are geolocation plugins specifically for backgrounding, and they are quite a bit more battery friendly, such as this [plugin](https://www.npmjs.com/package/cordova-plugin-mauron85-background-geolocation).

>> optional callback to pass into .stop() and .kill() that will be called when all is said and done?

Good call.
