### ISSUE TITLE
Ionic 2 / ionic 3 : unable to get "gps" , "network" and "satellite" ' s provider objects

### ISSUE THREAD

**Issue by kumarkundan** [Esri/cordova-plugin-advanced-geolocation#57]
This plugin **was working fine for me till yesterday** , and i was using it in one of my ionic2 apps. But suddenly from today it's stopped working . It's not working for any of my 2-3 ionic apps. ealier it was working for all those apps.

On Debugging and checking console , I was surprised that in success of  ` AdvancedGeolocation.start((success)` i was only getting these two types of provider objects :- 

`{"provider":"cell_info","type":"wcdma","timestamp":1510306725281,"cid":2147483647,"lac":2147483647,"mcc":2147483647,"mnc":2147483647,"psc":252}`

`{"provider":"cell_location","type":"gsm","timestamp":1510307383757,"cid":167954,"lac":25,"psc":-1}`

i am not getting "gps" , "network" and "satellite" ' s provider objects at all.

here is sample code that i have been using . 

```
if (this.platform.is('android')) {
            this.platform.ready().then(() => {
                AdvancedGeolocation.start((success) => {

                    try {
                        var jsonObject = JSON.parse(success);
                        console.log("Provider " + JSON.stringify(jsonObject));
                        switch (jsonObject.provider) {
                            case "gps":
                                console.log("setting gps ====<<ppp>>" + JSON.stringify(jsonObject));

                                this.currentLat = jsonObject.latitude;
                                this.currentLng = jsonObject.longitude;

                                break;

                            case "network":
                                console.log("setting network ====<<ppp>>" + JSON.stringify(jsonObject));

                                this.currentLat = jsonObject.latitude;
                                this.currentLng = jsonObject.longitude;

                                break;

                            case "satellite":
                                //TODO
                                break;

                            case "cell_info":
                                //TODO
                                console.log("hiiii bhaeeeereeerrrrrr");
                                
                                break;

                            case "cell_location":
                                //TODO
                                break;

                            case "signal_strength":
                                //TODO
                                break;
                        }
                    }
                    catch (exc) {
                        console.log("Invalid JSON: " + exc);
                    }
                },
                    function (error) {
                        console.log("ERROR! " + JSON.stringify(error));
                    },
                    {
                        "minTime": 500,         // Min time interval between updates (ms)
                        "minDistance": 1,       // Min distance between updates (meters)
                        "noWarn": true,         // Native location provider warnings
                        "providers": "all",     // Return GPS, NETWORK and CELL locations
                        "useCache": true,       // Return GPS and NETWORK cached locations
                        "satelliteData": false, // Return of GPS satellite info
                        "buffer": false,        // Buffer location data
                        "bufferSize": 0,         // Max elements in buffer
                        "signalStrength": false // Return cell signal strength data
                    });

            });
        }
```

**Comment by andygup** [comment]
Did you see any native Android errors in [logcat (available via Android Studio)](https://developer.android.com/studio/debug/am-logcat.html) when you started the app? That is always the first thing that I check.

Here are some suggestions:
- Double check that location is enabled for each app
- Run a quick Geolocation test. Open this browser-based test app and see if it returns a location? https://esri.github.io/html5-geolocation-tool-js/

**Comment by kumarkundan** [comment]
hii @andygup , today i again checked . now everything is working fine. For your info , i have not changed a single word in my code base. 

Now i am getting all the objects in provider , earlier i was getting only `cell_info` and `cell_location` . That means , i was not getting other provider's objects.

I want to ask you this . Whether `**cordova-plugin-advanced-geolocation**` is reliable or not . I can use this in production environment or not. Because it seems like , sometimes it's working and sometimes it's not.

You tell me , what to do . Again I have not changed a single word in code base and now it's working fine .

B/W thanks a lot for helping me out.

**Comment by andygup** [comment]
@kumarkundan Given the intermittent nature of the problem, this appears to be an issue with your cell phone provider. For example, the value `2147483647` in the response object tells me that a particular cell phone tower is simply not providing the information you want. 

As far as I know, there are generally no international requirements that cellular towers provide any of this information consistently or at all.

My recommendation is to write your code to gracefully handle the situations where the cell provider does not provide information.

Does that make sense?

**Comment by andygup** [comment]
Closing this issue. It's a problem with the cellular service provider.
