### ISSUE TITLE
the plugin freezes my app - ionic 3

### ISSUE THREAD

**Issue by alejox21** [Esri/cordova-plugin-advanced-geolocation#59]
Hello, I'm using the plugin in my app for get the gps location timestamp (beacuse I need the real datetime from the place where i'm, independent from the device, and also internet network connection may not be available or possible), the value obtained it's ok, but freezes the app...

ionic 3.19.0
cordova 7.0.1
device: android 5.1

my code: I implemented a service with a function that returns the location timestamp, in the page the function buttonGettime() sets the variable "tiempo" that display the timestamp on button tap at html page

service.ts:

`import { Injectable } from '@angular/core';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/operator/map';

declare var AdvancedGeolocation:any;

@Injectable()
export class Service {

  constructor() {}

  getTime():Promise<string>{
    return new Promise(function (resolve, reject) {
      AdvancedGeolocation.start(function (data) {
        try{
          let location = JSON.parse(data);
          resolve(location.timestamp);
        }
        catch (error) {
          reject(error);
        }
      }.bind(this), // bind explicitly to this
        function (error) {
          reject(error);
        }, {
          "minTime": 500,         // Min time interval between updates (ms)
          "minDistance": 1,       // Min distance between updates (meters)
          "noWarn": true,         // Native location provider warnings
          "providers": "all",     // Return GPS, NETWORK and CELL locations
          "useCache": true,       // Return GPS and NETWORK cached locations
          "satelliteData": false, // Return of GPS satellite info
          "buffer": false,        // Buffer location data
          "bufferSize": 0,        // Max elements in buffer
          "signalStrength": false // Return cell signal strength data
        });
    }.bind(this));
  };

  stopTime():Promise<string>{
    return new Promise((resolve, reject) => {
      AdvancedGeolocation.stop(
        function(success){
          var jsonObject = JSON.parse(success);
          resolve(JSON.stringify(jsonObject.stopLocation));
        },
          function(error){
            reject(JSON.stringify(error));
          },
      );
    })
  };

}
`

page.ts:
`import { Service } from '../../providers/service/service';

@IonicPage()
@Component({
  selector: 'page-page',
  templateUrl: 'page.html',
})
export class PagePage {
tiempo : any = 0;

constructor(
              public service: Service,
              )
              {}

//function button start service, sets "tiempo" variable
buttonGettime(){
    //get time advanced geolocation
    this.service.getTime().then( obtenido =>{
        this.tiempo = obtenido;
      }
    ).catch((err) => {
                     this.handleError(err)
                   }
                 );
  }

//function stop()
  buttonStoptime(){
    this.service.stopTime().then( detenido =>{
        }
      ).catch((err) => {
                       this.handleError(err)
                     }
                   );
  }
}
`

page.html:
`<ion-content>
  < p >Timestamp:</strong>{{tiempo}}< /p >
  < button ion-button large full (tap)="buttonGettime()" color="danger" >
    Tiempo
  < /button >

  < br />
  < button ion-button large full (tap)="buttonStoptime()" color="danger" >
    Tiempo Detener
  </ button >
  < br />
< ion-content >
`

sorry for my bad english... (also im still noob in ionic), thank for your help

**Comment by alejox21** [comment]
sorry my bad, hope I edited properly

**Comment by andygup** [comment]
You'll need to remote debug your app. Do you see any errors?

Reference: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

**Comment by andygup** [comment]
Closing out. Feel free to reopen.

**Comment by BossAustralia** [comment]
Hello,

I have the same problem, the freeze, but I don't receive any error in the console.

**Comment by JoelDoitlean** [comment]
Hello,

I have the same problem, the app freeze, but I don't receive any error in the console.

**Comment by alejox21** [comment]
Hello, sorry, but at the end i changed to another plugin. Looking at my code above now, maybe the attributes configuration was not configured properly and the method stopTime() it was not well written by me, then time does not stop

**Comment by andygup** [comment]
If you don't have any browser console errors you will need to debug the phone using logcat and look for device errors coming from the Android operating system. This may or may not be related to incorrect thread pooling design in the Cordova bridge.

I'm not able reproduce and without additional information or error messages I can't figure it out.
