### ISSUE TITLE
is-it possible to use advanced-geolocation plugin in the background

### ISSUE THREAD

**Issue by spinella1anthony** [Esri/cordova-plugin-advanced-geolocation#64]
hello everyone, 

Is-it possible to use this plugin in the backgroud? 

Thanks in advance

**Comment by andygup** [comment]
This plugin isn't designed to run in the background. Because of its potential to consume large amounts of memory and CPU cycles it will only provide locations, by default, while the application is in the foreground and active.

**Comment by spinella1anthony** [comment]
Thanks for your answer.
Is there an other way to obtain SatelliteData in background?

**Comment by andygup** [comment]
If you want you can make a copy or fork this repo and customize the functionality for the `onStop` and `onPause` listeners: https://github.com/Esri/cordova-plugin-advanced-geolocation/blob/master/src/com/esri/cordova/geolocation/AdvancedGeolocation.java#L431-L439

**Comment by andygup** [comment]
Closing, feel free to reopen if necessary.
