### ISSUE TITLE
Network as provider while mocking using an application

### ISSUE THREAD

**Issue by atiato** [Esri/cordova-plugin-advanced-geolocation#73]
Hello , 
We are facing issue while getting geolocation using network as provider if mock on android device is enabled.
following screen shots while doing that 
mocking is disabled and same location is used.
![WhatsApp Image 2020-03-19 at 10 41 41 PM](https://user-images.githubusercontent.com/652472/77171781-a22a3c80-6ac5-11ea-862d-42a8b63e9210.jpeg)
mocking is enabled here.
![WhatsApp Image 2020-03-19 at 10 42 08 PM](https://user-images.githubusercontent.com/652472/77171836-b1a98580-6ac5-11ea-8623-437c907998b6.jpeg)

why this is happening even we are getting information from network not from gps device embedded on the phone.

thanks,
Omar

**Comment by andygup** [comment]
Hi Omar, I'm not sure I understand the issue you are having? You can always reject non-mock locations by verifying where they come from: https://developer.android.com/reference/android/location/Location#isFromMockProvider(). 

Android devices will send network and gps location information unless those providers have been disabled by the user, operating system, or thru code.

**Comment by andygup** [comment]
Closing.
