### ISSUE TITLE
neighbouring cells by provider cell

### ISSUE THREAD

**Issue by atiato** [Esri/cordova-plugin-advanced-geolocation#74]
Hello ,

I'm trying to get neighbouring cells but unable to do so , I'm getting only cid that I'm connected to !

Do you have any configuration to help me to get these neigboring cells in order to geolocate the device using opencellID API with more accuracy .

thanks,
Omar Atia

**Comment by andygup** [comment]
Hi Omar, I don't have any suggestions, I haven't used that API in quite a while. Maybe try https://android.stackexchange.com/?

**Comment by andygup** [comment]
Closing.
